name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock') }}

      - name: Install dependencies
        run: npm install

      - name: Run Style Code
        run: npm run style

      - name: Run lint
        run: npm run lint

      - name: Unit testing
        run: npm run test --code-coverage

      - name: E2E
        run: npm run e2e

      - name: Build Prod
        run: npm run build:prod

      - name: AutoMege DependaBot
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT }}
